@startuml
package models {
    class Card
    class Labelling
    class Search
    abstract class Model
    Card --|> Model
    Card *-- Labelling
}

package activities{
    package fragments{
    }
    class CardDataActivity
    class CardsAdpater
    class HomeActivity
    class SearchCardsActivity
    class MainActivity
}

package controllers {
    class CardController
}

package repositories{
    package datastores {
        package technologies{
            abstract class DataStore
            DataStore <|-- FirestoreDataStore
            DataStore *-- CardQueryResultListener
            DataStore *-- ModelMapper
        }
        abstract class CardDataStore
        CardDataStore *-- CardQueryResultListener
        CardDataStore <|-- FirestoreCardDataStore
        CardDataStore ..|> CardQueryResultListener
        class FirestoreDataStore<T>
        FirestoreCardDataStore --> FirestoreDataStore
    }
    package mappers {
        interface ModelMapper
        ModelMapper --> Model
        CardMapper ..|> ModelMapper
        CardMapper --> Card
    }
    interface CardQueryResultListener
    interface CardRepository
    class CardDataRepository
    CardView ..|> CardQueryResultListener
    CardController *-- CardView
    CardController --> CardRepository
    CardDataRepository ..|> CardRepository
    CardDataRepository --> CardDataStore


}
@enduml