@startuml
package controllers {
    class CardController


}
package models {
    class Card
    class Labelling
    class Search
    abstract class Model
    Card -right-|> Model
    Card *-- Labelling
}

package activities{
    package fragments{
    }
    class CardDataActivity
    class CardsAdpater
    class HomeActivity
    class SearchCardsActivity
    class MainActivity

    abstract class CardView
    CardView -up-> CardController
    CardView <|-- CardDataActivity
    CardView <|-- SearchCardsActivity
}

package repositories{
    CardController -down-> CardRepository
    package mappers {
        interface ModelMapper
        ModelMapper --> Model
        CardMapper ..|> ModelMapper
        CardMapper --> Card
    }
    interface CardRepository
    interface DataStoreListener
    class CardFirestoreRepository
    CardFirestoreRepository ..|> CardRepository
    CardFirestoreRepository --> FirestoreDataStore

    class FirestoreDataStore<T>
    FirestoreDataStore *-- DataStoreListener
    FirestoreDataStore *-- ModelMapper
    CardController *-- DataStoreListener
    CardView ..|> DataStoreListener
}

@enduml