@startuml

skinparam nodesep 100
hide methods
hide attributes
hide stereotypes

title Evermind - Domain model\n

class User
class Author
class Subscription
class Card
class Question
class Answer
class Label
class Search
class Keyword
class ReviewRound
class Level

User ..> Search
User o--> "0..*" Subscription
Author --|> User
Subscription *--> Card
User ..> ReviewRound
Subscription *--> Level
Card *--> "1..*" Label
Card *--> Author
Card *--> Question
Card *--> Answer
Search *--> "1..*" Keyword
Keyword -left-> "0..1" Author
Keyword --> "0..*" Label
ReviewRound *--> "1..10" Subscription


@enduml
