@startuml

title __FIELDS's Class Diagram__\n

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace fields {
        enum AuthError {
          EMAIL_EXIST
          ON_LOGIN
          ON_REGISTER
          USERNAME_EXIST
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace fields {
        enum CardField {
          ANSWER
          AUTHOR_ID
          AUTHOR_USERNAME
          ID
          LABELLING
          LABEL_LIST_SEPARATOR
          QUESTION
          value
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace fields {
        enum DataStoreError {
          ON_DELETE
          ON_INSERT
          ON_LOAD
          ON_LOAD_ALL
          ON_RESET_PASSWORD_NOT_SENT
          ON_RESET_PASSWORD_SENT
          ON_SEARCH
          ON_UPDATE
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace fields {
        enum FirestoreCollectionsLabels {
          CARD
          SUBSCRIPTION
          USER
          value
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace fields {
        enum SubscriptionField {
          CARD_ID
          LAST_REVIEW
          LEVEL
          NEXT_REVIEW
          USER_ID
          value
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace fields {
        enum UserField {
          AUTH_ID
          DAY_START_TIME
          EMAIL
          LAST_CONNECTION
          LAST_LOGIN
          NAME
          SIGN_IN
          STATUS
          USERNAME
          USER_ID
          value
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
