@startuml

title __LISTENERS's Class Diagram__\n

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace listeners {
        interface com.ferllop.evermind.repositories.listeners.AuthListener {
            {abstract} + onAuthActionResult()
            {abstract} + onError()
            {abstract} + onLogin()
            {abstract} + onRegister()
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace listeners {
        enum AuthMessage {
          LOG_OUT
          RESET_PASSWORD_EMAIL_NOT_SENT
          RESET_PASSWORD_EMAIL_SENT
          USER_VERIFIED
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace listeners {
        interface com.ferllop.evermind.repositories.listeners.CardDataStoreListener {
            {abstract} + onDelete()
            {abstract} + onError()
            {abstract} + onLoad()
            {abstract} + onLoadAllCards()
            {abstract} + onSave()
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace listeners {
        interface com.ferllop.evermind.repositories.listeners.CrudDataStoreListener {
            {abstract} + onDelete()
            {abstract} + onError()
            {abstract} + onLoad()
            {abstract} + onLoadAll()
            {abstract} + onSave()
            {abstract} + onUserDataStoreResult()
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace listeners {
        enum DataStoreMessage {
          NOT_FOUND
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace listeners {
        interface com.ferllop.evermind.repositories.listeners.SubscriptionDataStoreListener {
            {abstract} + onDelete()
            {abstract} + onError()
            {abstract} + onLoad()
            {abstract} + onLoadAllSubscriptions()
            {abstract} + onSave()
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace listeners {
        interface com.ferllop.evermind.repositories.listeners.UserDataStoreListener {
            {abstract} + emailExists()
            {abstract} + onAuthActionResult()
            {abstract} + onDelete()
            {abstract} + onError()
            {abstract} + onLoad()
            {abstract} + onLoadAll()
            {abstract} + onSave()
            {abstract} + usernameExists()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
