@startuml

title __MAPPERS's Class Diagram__\n

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace mappers {
        class com.ferllop.evermind.repositories.mappers.CardMapper {
            + execute()
            + execute()
            - booleanMapToList()
            - listToBooleanMap()
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace mappers {
        interface com.ferllop.evermind.repositories.mappers.ModelMapper {
            {abstract} + execute()
            {abstract} + execute()
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace mappers {
        class com.ferllop.evermind.repositories.mappers.SubscriptionMapper {
            + execute()
            + execute()
        }
      }
    }
  }
  

  namespace com.ferllop.evermind {
    namespace repositories {
      namespace mappers {
        class com.ferllop.evermind.repositories.mappers.UserMapper {
            + execute()
            + execute()
        }
      }
    }
  }
  

  com.ferllop.evermind.repositories.mappers.CardMapper .up.|> com.ferllop.evermind.repositories.mappers.ModelMapper
  com.ferllop.evermind.repositories.mappers.SubscriptionMapper .up.|> com.ferllop.evermind.repositories.mappers.ModelMapper
  com.ferllop.evermind.repositories.mappers.UserMapper .up.|> com.ferllop.evermind.repositories.mappers.ModelMapper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
